### ISSUE TITLE
Build warnings on 1.1.0 in the "public repository"

### ISSUE THREAD

**Issue by lws-team** [ARMmbed/sal-stack-lwip#39]
/home/agreen/projects/mbed/mbed3-dumb-http-test/yotta_modules/sal-stack-lwip/sal-stack-lwip/lwip/include/ipv4/lwip/ip_addr.h:213:23: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   LWIP_DEBUGF(debug, ("%"U16_F".%"U16_F".%"U16_F".%"U16_F,             \
                       ^
/home/agreen/projects/mbed/mbed3-dumb-http-test/yotta_modules/sal-stack-lwip/sal-stack-lwip/lwip/include/ipv4/lwip/ip_addr.h:213:31: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   LWIP_DEBUGF(debug, ("%"U16_F".%"U16_F".%"U16_F".%"U16_F,             \
                               ^
/home/agreen/projects/mbed/mbed3-dumb-http-test/yotta_modules/sal-stack-lwip/sal-stack-lwip/lwip/include/ipv4/lwip/ip_addr.h:213:40: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   LWIP_DEBUGF(debug, ("%"U16_F".%"U16_F".%"U16_F".%"U16_F,             \
                                        ^
/home/agreen/projects/mbed/mbed3-dumb-http-test/yotta_modules/sal-stack-lwip/sal-stack-lwip/lwip/include/ipv4/lwip/ip_addr.h:213:49: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   LWIP_DEBUGF(debug, ("%"U16_F".%"U16_F".%"U16_F".%"U16_F,             \
                                                 ^
[208/209] Building CXX object source/CMakeFiles/test1.dir/home/agreen/projects/mbed/mbed3-dumb-http-test/source/app.cpp.o
In file included from /home/agreen/projects/mbed/mbed3-dumb-http-test/yotta_modules/sal-stack-lwip/sal-stack-lwip/lwip/include/lwip/netif.h:41:0,
                 from /home/agreen/projects/mbed/mbed3-dumb-http-test/yotta_modules/sal-iface-eth/sal-iface-eth/EthernetInterface.h:25,
                 from /home/agreen/projects/mbed/mbed3-dumb-http-test/source/app.cpp:2:
/home/agreen/projects/mbed/mbed3-dumb-http-test/yotta_modules/sal-stack-lwip/sal-stack-lwip/lwip/include/ipv4/lwip/ip_addr.h:213:23: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   LWIP_DEBUGF(debug, ("%"U16_F".%"U16_F".%"U16_F".%"U16_F,             \
                       ^
/home/agreen/projects/mbed/mbed3-dumb-http-test/yotta_modules/sal-stack-lwip/sal-stack-lwip/lwip/include/ipv4/lwip/ip_addr.h:213:31: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   LWIP_DEBUGF(debug, ("%"U16_F".%"U16_F".%"U16_F".%"U16_F,             \
                               ^
/home/agreen/projects/mbed/mbed3-dumb-http-test/yotta_modules/sal-stack-lwip/sal-stack-lwip/lwip/include/ipv4/lwip/ip_addr.h:213:40: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   LWIP_DEBUGF(debug, ("%"U16_F".%"U16_F".%"U16_F".%"U16_F,             \
                                        ^
/home/agreen/projects/mbed/mbed3-dumb-http-test/yotta_modules/sal-stack-lwip/sal-stack-lwip/lwip/include/ipv4/lwip/ip_addr.h:213:49: warning: invalid suffix on literal; C++11 requires a space between literal and string macro [-Wliteral-suffix]
   LWIP_DEBUGF(debug, ("%"U16_F".%"U16_F".%"U16_F".%"U16_F,             \

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1467

**Comment by niklas-arm** [comment]
:+1:.
In total there are almost 200 instances of the `U16_F` string in this module.
We would have to replace then all, and therefore modify LWIP code?
cc @bremoran
