### ISSUE TITLE
It is not possible to query the size of a UDP packet before receiving it.

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/sal-stack-lwip#51]
Unread UDP data in a packet is discarded after the first read of that packet. This is inline with BSD sockets, however, this may not be appropriate on mbed. This is complicated by the lack of a query API to determine the length of a packet in the ```onReceive``` API.

To solve this, the simplest solution is to add a special case of ```recv()``` with 0 length, indicating that the API should fill the size of the current packet and retain the current packet.

A more complete solution is to add the length of the packet (UDP) or the size of available data (TCP) to the ```onReceive``` API.

For UDP, the best solution would be one which provides an API that allows partial reads in the ```onReceive``` handler, but discards any remainder at the end of the handler.

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-1956
