### ISSUE TITLE
error: unknown type name 'size_t' in cc.h

### ISSUE THREAD

**Issue by cyliangtw** [ARMmbed/sal-stack-lwip#61]
Set target **nu-nuc472-nubed-gcc** and encounter  **_unknown type name 'size_t'_** in building.
After traced **cc.h** , it seems header file issue and resolved by adding **stddef.h** as below: 
```
#ifndef __CC_H__
#define __CC_H__

#include <stdint.h>
#include <stddef.h> /* for size_t */
```

**Comment by ciarmcom** [comment]
ARM Internal Ref: IOTSFW-2488
